"use client";

import { useState, useEffect } from "react";
import { getAttendanceHistory } from "@/app/actions/reports";

type Session = {
  id: string;
  clockIn: Date;
  clockOut: Date | null;
  workDate: string;
  regularHours: number | null;
  otHours: number | null;
};

export function AttendanceView() {
  const [sessions, setSessions] = useState<Session[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    async function load() {
      try {
        const data = await getAttendanceHistory(30); // Last 30 sessions
        setSessions(data as Session[]);
      } catch (err) {
        console.error(err);
      } finally {
        setIsLoading(false);
      }
    }
    load();
  }, []);

  const handleExportPDF = () => {
    window.print();
  };

  if (isLoading) {
    return <div className="animate-pulse space-y-4">
      {[1,2,3].map(i => <div key={i} className="h-20 bg-muted rounded-xl w-full"></div>)}
    </div>;
  }

  return (
    <div className="space-y-4">
      <div className="flex justify-between items-center gap-4 mb-6">
        <h2 className="text-lg font-semibold text-foreground">Recent Attendance</h2>
        {/* Hide this button during printing */}
        <button 
          onClick={handleExportPDF}
          className="print-hide px-4 py-2 bg-primary/10 text-primary hover:bg-primary/20 rounded-lg font-medium text-sm transition-colors flex items-center gap-2 flex-shrink-0"
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
          Export PDF
        </button>
      </div>

      {sessions.length === 0 ? (
        <p className="text-center text-muted-foreground py-12">No attendance records found.</p>
      ) : (
        <div className="space-y-3">
          {sessions.map((session) => {
            const dateObj = new Date(session.workDate + "T00:00:00");
            const duration = (session.regularHours || 0) + (session.otHours || 0);
            
            // Format time accurately
            const inTime = new Date(session.clockIn).toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' });
            const outTime = session.clockOut ? new Date(session.clockOut).toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' }) : "Active";

            return (
              <div key={session.id} className="glass p-4 md:p-5 rounded-xl border border-border break-inside-avoid hover:border-border/80 transition-colors">
                <div className="flex justify-between items-start gap-4 mb-3">
                  <p className="font-semibold text-foreground text-sm">
                    {dateObj.toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' })}
                  </p>
                  <p className="font-bold tabular-nums text-primary text-sm">{duration.toFixed(2)}h</p>
                </div>
                
                <div className="flex items-center gap-2 text-xs text-muted-foreground">
                  <div className="flex items-center gap-1.5">
                    <span className="w-2 h-2 rounded-full bg-success flex-shrink-0"></span>
                    <span>{inTime}</span>
                  </div>
                  <span className="text-muted-foreground/50">→</span>
                  <div className="flex items-center gap-1.5">
                    <span className={`w-2 h-2 rounded-full flex-shrink-0 ${session.clockOut ? 'bg-destructive' : 'bg-warning animate-pulse'}`}></span>
                    <span>{outTime}</span>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
      
      {/* Footer text only visible in print mode */}
      <div className="hidden print:block text-center text-xs text-muted-foreground mt-8 pt-4 border-t border-border">
        Generated by ShiftSync Time Tracking • {new Date().toLocaleDateString()}
      </div>
    </div>
  );
}
